### PR TITLE
Tidy/webpack config

### PR DESCRIPTION
**Pull request by thomasdigby**

### CODE REVIEW

**Comment by thomasdigby** [comment]
@jonsherrard What are your thoughts on this update? I think it still separates out the differing config set-ups clearly but without the `whenEnv` logic.

`Object.assign()` is king

**Comment by thomasdigby** [comment]
I don't know why this is bumping up the build time to ~25secs... the configs returned for each context (node, dev etc.) are exact matches. 🤔

**Comment by jonsherrard** [comment]
It's because you've removed the turbo power of `whenEnvIs`, authored by coffee and delirium.

**Comment by thomasdigby** [comment]
😕

**Pull request merged**
