### PR TITLE
CSS Migration Mode

### PR DESCRIPTION
**Pull request by jonsherrard**
Hacked up a little thoughtlet PR:

> What if you could start writing new components with Emotion and have your legacy components render with Glamor?

I need to do some client-side testing around Client-side CSS updates (styles dependent on interaction and component state), but the SSR implementation works. Edit: (I have now done this see below)

I'll also need to check what adding Emotion and Glamor does to bundle sizes.

> *I've done this*: It added 24kb to the vendor bundle. Something to bear in mind but potentially a worthy trade off to use a snazzier CSS-In-JS solution sooner.

This might be a dumb idea and migrating a project manually might be less faff...

Here's the client test:

```js
import React from 'react'
import styled from 'react-emotion'
import { css } from 'glamor'

class Test extends React.Component {
  constructor() {
    super()
    this.state = {
      color: 'red'
    }
  }
  componentDidMount() {
    setInterval(() => {
      this.setState({color: (this.state.color === 'red') ? 'blue' : 'red'})
      console.log(this.state.color)
    }, 1000)
  }

  render() {
    const EmotionText = styled('p')`
      color: ${this.state.color}
    `
    return (
      <div>
        <EmotionText>Red</EmotionText>
        <p className={css({color: this.state.color})}>
          Blue
        </p>
      </div>
    )
  }
}

export default Test
```

And here's the result:

emotion-and-glamor

Glamor and Emotion doing their thing simultaneously! Pretty mental, but would let us crack on writing Emotion powered stuff in legacy projects.

## Bundle size on legacy project (ray) using only glamor:

screen shot 2018-04-25 at 22 22 26

## Bundle size on legacy project (ray) using in migration mode (glamor and emotion)

screen shot 2018-04-25 at 22 22 38

### CODE REVIEW

**Comment by thomasdigby** [comment]
Jon. You're on holiday man. Take a break.

(_however, this is looking fly!_)

**Comment by jonsherrard** [comment]
What do you think any desire to write Emotion code in legacy proj's?

**Comment by thomasdigby** [comment]
@jonsherrard I'm 50/50. I think we can kick on with Emotion in new projects and possibly just update Lennon to emotion in one fell swoop.

However it's not a large change so we could get it in and just work with both.

**Comment by jonsherrard** [comment]
Let's close - pretty easy to reimplement, and I think just cracking on with a migration is probably as much work.

**Pull request closed without merging**
